{
  "errors": [
    {
      "code": 3,
      "level": "warn",
      "message": "\u001b[31m\u001b[41m\u001b[22m\u001b[24m[\u001b[0m\u001b[38;5;231m\u001b[41m\u001b[1m\u001b[24mWARN\u001b[0m\u001b[31m\u001b[41m\u001b[22m\u001b[24m]\u001b[0m Syntax error at line targets/bad/invalid_python.py:1:\n `\n    ` was unexpected",
      "path": "targets/bad/invalid_python.py",
      "type": "Syntax error"
    }
  ],
  "paths": {
    "scanned": [
      "targets/bad/invalid_python.py"
    ],
    "skipped": [
      {
        "path": "targets/bad/invalid_python.py",
        "reason": "analysis_failed_parser_or_internal_error"
      }
    ]
  },
  "results": [],
  "version": "0.42"
}